### ISSUE TITLE
pass $value to composable child view

### ISSUE THREAD

**Issue by wryk** [ripplejs/each#2]
Hi ! I'm writting a TodoMVC app with component and ripple but I got `Uncaught TypeError: Cannot read property 'completed' of undefined` in a VM with something like this : 

``` html
<ul id="todo-list" each="{{todos}}">
    <todo todo="{{$value}}"></todo>
</ul>
```

``` html
<li completed="{{todo.completed}}">
    <div class="view" on-dblclick="{{this.edit}}">
        <input class="toggle" type="checkbox" ref="completed" checked="{{todo.completed}}" on-change="{{this.updateState}}">
        <label>{{todo.title}}</label>
        <button class="destroy" on-click="{{this.delete}}"></button>
    </div>
    <input class="edit" value="{{todo.title}}" on-enter="{{this.save}}">
</li>
```

`$index` pass fine but i don't know how to pass a 'todo' object from the 'todos' array.
I'm doing something weird ?

**Comment by wryk** [comment]
It's my fault, I use a custom parse function and forgot to take care about `options.data` :<

``` javascript
Todo.parse = function (options) {
    return {
        editing: false
        // I forgot to pass options.data.todo like
        // todo: options.data.todo
    };
};
```

It's fixed now but I just ran into a memory leak, i'll inspect it.

EDIT: Yeah, recursive $value property cause the leak, I'll think about make a PR

**Comment by wryk** [comment]
@anthonyshort What do you think about this use case and this leak ?

**Comment by anthonyshort** [comment]
This is a tricky issue. I didn't think the `each` plugin would be used with sub-views, at least in it's current state. It's pretty simple at the moment. I'm writing a better list module now that should make things easier.

It might be easier for now to just render the list of todos manually.

``` js
var App = ripple(template);

App.on('created', function(app){
  var fragment = document.createDocumentFragment();
  app.get('todos').forEach(function(todo){
     var view = new Todo(todo);
     fragment.appendChild(view.el);
  });
  app.set('todos', fragment);
});
```

``` html
<ul id="todo-list">
    {{todos}}
</ul>
```

It'll render the fragment in there just fine. I think this is a lot simpler than using the `each` plugin which has to do some pretty complex stuff when it really doesn't need to.

The `List` component I'm writing should make this easier. I could also make the view know how to render arrays of elements/views too so you could just do:

``` js
App.on('created', function(app){
  app.set('todos', []);
});
App.prototype.createTodo = function(todo){
  return new Todo(todo).el;
};
```

``` html
<ul>{{todos | createTodo}}</ul>
```

**Comment by wryk** [comment]
Oh, I understand the use case now, thank you for your answer !
I'm looking forward to testing this module :D
